# Generated by Django 4.2.5 on 2023-09-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode_img',
            field=models.ImageField(upload_to='files/qrcode_images'),
        ),
    ]
