# Generated by Django 4.2.5 on 2023-09-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_alter_qrcode_qrcode_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='data',
            field=models.CharField(default='none', max_length=9999),
        ),
    ]
