# Generated by Django 4.2.5 on 2023-10-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0004_rename_qrcode_img_qrcode_img_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="img_file",
        ),
        migrations.AddField(
            model_name="qrcode",
            name="data_uri",
            field=models.CharField(default="none", max_length=9999),
        ),
    ]
