# Generated by Django 4.2.5 on 2023-10-02 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0005_remove_qrcode_img_file_qrcode_data_uri"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrcode",
            old_name="data",
            new_name="qr_data",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="data_uri",
        ),
    ]
