# Generated by Django 4.2.5 on 2023-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_rename_data_qrcode_qr_data_remove_qrcode_data_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
